Conversation = require('hubot-conversation')

module.exports = (robot) ->
  switchBoard = new Conversation(robot)
  robot.respond /clean the house/, (msg) ->
    dialog = switchBoard.startDialog(msg)
    msg.reply 'Sure, where should I start? Kitchen or Bathroom'
    dialog.addChoice /kitchen/i, (msg2) ->
      msg2.reply 'On it boss!'
      return
    dialog.addChoice /bathroom/i, (msg2) ->
      msg.reply 'Do I really have to?'
      dialog.addChoice /yes/, (msg3) ->
        msg3.reply 'Fine, Mom!'
        return
      return
    return
  robot.respond /jump/, (msg) ->
    dialog = switchBoard.startDialog(msg)
    msg.reply 'Sure, How many times?'
    dialog.addChoice /([0-9]+)/i, (msg2) ->
      times = parseInt(msg2.match[1], 10)
      i = 0
      while i < times
        msg.emote 'Jumps'
        #We can use the original message too.
        i++
      return
    return
  robot.respond /.*the mission/, (msg) ->
    msg.reply 'Your have 5 seconds to accept your mission, or this message will self-destruct'
    dialog = switchBoard.startDialog(msg, 5000)
    #5 Second timeout

    dialog.timeout = (msg2) ->
      msg2.emote 'Boom'
      return

    dialog.addChoice /yes/i, (msg2) ->
      msg2.reply 'Great! Here are the details...'
      return
    return
  return

# ---
# generated by js2coffee 2.2.0